/** @type {import('tailwindcss').Config} */
// @vite('resources/css/app.css)
module.exports = {
    content: [
        "./resources/**/**/*.blade.php",
        "./resources/**/**/*.js",
        "./resources/**/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                black: "#171717",
                dark: "#333",
                mainColor: "#DA0037",
                "light-one": "#fff",
                "light-two": "#f9fafb",
                "light-three": "#ededed",
                navBackground: "rgba(23, 23, 23, 0.8)",
                "light-transparent": "rgba(237, 237, 237, 0.8)",
                primary: {
                    50: "#eff6ff",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                },
            },
        },
        fontFamily: {
            body: [
                "Inter",
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "system-ui",
                "Segoe UI",
                "Roboto",
                "Helvetica Neue",
                "Arial",
                "Noto Sans",
                "sans-serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "Noto Color Emoji",
            ],
            sans: [
                "Inter",
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "system-ui",
                "Segoe UI",
                "Roboto",
                "Helvetica Neue",
                "Arial",
                "Noto Sans",
                "sans-serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "Noto Color Emoji",
            ],
        },
    },
    plugins: [],
};
